### ISSUE TITLE
Meaning of 'len_closeness'

### ISSUE THREAD

**Issue by cccathyhhhhh66688** [HuiqunHuang/EVL#1]
Hello, I am currently trying to learn your code. I would like to ask what does 'len_closeness' and 'len_day' in the code mean? Does 'category_num=8' mean that there are 8 types of bicycle data and 8 categories of data are predicted at the same time?

**Comment by HuiqunHuang** [comment]
Hi, 
1: category_num means the number of both the input and target objects in this model. For example, if you want to predict the future dynamic of 8 regions of the city, then category_num is 8.

2:  'len_closeness' and 'len_day' mean the number of the near history time intervals and number of days, respectively. Say that there are T time intervals within a day (the length of each time interval is 24/T hours), and we want to predict the dynamics of target objects in a randomly selected target time interval l+1. Then,

   a) The model takes in the near history time series data of all the target objects during {l-len_closeness+1, l-len_closeness+2,...,l}, which is denoted as near_category_X in the codes. Taking in near_category_X is because we want to predict the dynamic of all target objects by capturing the temporal patterns of  the near history time series data.

   b) The model also takes in the len_day days of previous time series data of all target objects and len_day - 1 time intervals of extreme label. Using these data,  we are aiming at 1) capture the temporal patterns of the time series data of all objects; 2) capture the temporal correlations among time series data of each object and the corresponding extreme labels, and 3) predict the extreme labels of each target object in the target time interval l+1. All the above three aims can be done by feeding the previous T time intervals of time series data into LSTM/GRU to predict the extreme label of the following time interval. This operation is repeated len_day times and the output state of the previous LSTM/GRU can be the initialized state of current LSTM/GRU.

      Back to the details of the time range corresponding to len_day, the time series data here are not simply in the time range of {l-len_day * T+1, l-len_day * T+2,...,l}. Instead, they are the len_day days of time series data during time_range = [{l-len_day*T+1,...,l-(len_day-1)*T}, {l-(len_day-1)*T+1,...,l-(len_day-2)*T},...,{l-T+1,...,l}], where the length of the time intervals within each {} is T. In addition to the len_day days of time series data, the model also takes in len_day-1 time intervals of extreme label data of each target object. Each time intervals of the extreme labels here is corresponding to the next time interval of each {} in time_range. In particular, the len_day-1 time interval of the extreme labels are {l-(len_day-1)*T, l-(len_day-2)*T, ..., l-T+1}. The extreme labels in time intervals l+1 are the target extreme label to predicted.

**Comment by cccathyhhhhh66688** [comment]
Okay, thanks for your explanation, I learned a lot. I would also like to ask if len_closeness=2 and len_day=2 are the optimal values in the code? The model method is only applicable to data with periodicity, right? And are the parameters 'len_distribution' and 'len_trends' not used?

**Comment by HuiqunHuang** [comment]
> Okay, thanks for your explanation, I learned a lot. I would also like to ask if len_closeness=2 and len_day=2 are the optimal values in the code? The model method is only applicable to data with periodicity, right? And are the parameters 'len_distribution' and 'len_trends' not used?

For the values of len_closeness and len_day, I am not sure. I may change them to validate the parameters. You can test by running different settings.

For len_distribution and len_trends, yes, they are not used in the model. They are here cause I compare the result of this model with other works, so I have to use them to get the same data for all the model.

**Comment by cccathyhhhhh66688** [comment]
I got it. By the way, can I ask about the principle of EVL (y_true, y_red)?I don't quite understand the formula here

**Comment by HuiqunHuang** [comment]
> I got it. By the way, can I ask about the principle of EVL (y_true, y_red)?I don't quite understand the formula here

Try to read the loss function of the paper

**Comment by cccathyhhhhh66688** [comment]
The log(y_pred+0.01) in the Extreme Value Loss in the code, why is 0.01 more added compared to this paper? Do the 'evl_l1' and 'evl_l2' in the code correspond to the loss functions L1 and L2 in the paper?

**Comment by HuiqunHuang** [comment]
> The log(y_pred+0.01) in the Extreme Value Loss in the code, why is 0.01 more added compared to this paper? Do the 'evl_l1' and 'evl_l2' in the code correspond to the loss functions L1 and L2 in the paper?


logx, x has to be larger than 0. 0.01 here just to make x positive. Yes.

**Comment by cccathyhhhhh66688** [comment]
Thank you for taking the time to answer my questions.  It has helped me understand a lot.
